title: "test site"
author: "Rena Chong"
description: "hi"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
theme: jekyll-theme-slate

# Layout
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md"}
  - {file: "/_pages/about.md", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rena.chongpq@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/renachongpq"}
  - {title: Subscribe, icon: instagram, url: "https://www.instagram.com/"}

# comments:
# #  disqus_shortname: ""    # see https://disqus.com/
# #  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed


# # Site settings
# locale: "en-UK"
# name: "Rena"
# url: "https://renachongpq.github.io/"
# theme: jekyll-theme-slate


# # Site Footer
# footer:
# links:
#     - label: "Blog"
#       icon: "fas fa-fw fa-link"
#       url: "https://renachongpq.github.io/"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       # url: "https://twitter.com/"
#     - label: "Facebook"
#       icon: "fab fa-fw fa-facebook-square"
#       # url: "https://facebook.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       # url: "https://instagram.com/"


# markdown: kramdown
